sudo: false

dist: trusty

language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - php -r "printf('PHP %s', phpversion());"
  - composer self-update
  - composer install --no-interaction -o

script: ./vendor/bin/phpunit